let api = process.env.API_ROOT
export default {
  addPath: process.env.API_ROOT + '/addPath',
  addLoop: process.env.API_ROOT + '/addLoop',
  getLoopList: process.env.API_ROOT + '/getLoopList',
  deleteLoop: process.env.API_ROOT + '/deleteLoop',
  getLoop: process.env.API_ROOT + '/getLoop',
  editLoop: process.env.API_ROOT + '/editLoop',
  addBanner: process.env.API_ROOT + '/addBanner',
  getPath: process.env.API_ROOT + '/getPath',
  getPathList: process.env.API_ROOT + '/getPathList',
  getBanner: process.env.API_ROOT + '/getBanner',
  getBannerList: process.env.API_ROOT + '/getBannerList',
  getReserve: process.env.API_ROOT + '/getReserve',
  editPath: process.env.API_ROOT + '/editPath',
  deletePath: process.env.API_ROOT + '/deletePath',
  deleteBanner: process.env.API_ROOT + '/deleteBanner',
  deleteReserve: process.env.API_ROOT + '/deleteReserve',
  upload: process.env.API_ROOT + '/upload',
  addStrategy: api + '/addStrategy',
  getStrategy: api + '/getStrategy',
  getStrategyById: api + '/getStrategyById',
  editStrategy: api + '/editStrategy',
  deleteStrategy: api + '/deleteStrategy'
}